### ISSUE TITLE
README for charts/loki/loki not found

### ISSUE THREAD

**Issue by oke-py** [helm/hub#225]
README for charts/loki/loki is not found, and so it looks like loading.
https://hub.helm.sh/api/chartsvc/v1/assets/loki/loki/versions/0.22.0/README.md returns 404.

![loki](https://user-images.githubusercontent.com/4710215/71960313-0617c580-3238-11ea-91d4-5a3abc78275c.png)

I don't know whether this is helm hub's issue or loki's.

**Comment by andresmgot** [comment]
@oke-py the problem in your case is that the `urls` are not complete:

```
  - apiVersion: v1
    appVersion: v1.2.0
    created: 2020-01-08T08:12:23.012221912Z
    description: 'Loki: like Prometheus, but for logs.'
...
    urls:
    - loki-0.21.0.tgz
    version: 0.21.0
```

That url should be the complete URL to the tarball.
